---
title: "Final Report"
output: html_notebook
---

###Andrew Yan, Joey Johnson, Karen Kauffman

**Introduction:**
  
  For our final project we utilized a dataset that we found on kaggle on Pokemons from generation 1 to generation 6. The Pokemon data set comes in a clean easy to use format and it contains columns for each pokemon combat stat such as type, attack, defense and health. The dataset has a sizeable number of observations with 800 rows total. In our shiny app we aimed to find the differences in Pokemon stats between each generation and visualize these findings.
  
  
**Usage:**

  Our application utilized tabs to navigate which widget you want to select. Within each widget contains a dropdown menu of for each item to select. The graphs and data tables related to each tab displays information on the dataset depending on what you selected on the dropdown menu.
  
  
**Statistical Concepts:**

  In this project, we used confidence intervals to express "typical" stats for Pokemon of different types. Because the margin of error captures up to 2 standard deviations away from the mean, the bounds produced by the confidence intervals show that 99.7% of Pokemon of the given type should have the respective stat fall within those bounds. As a result, the interval is very large, but it seems appropriate - Pokemon games are designed to have some Pokemon who are easy to capture and relatively weak, and a few legendaries who are far harder to catch but have notably higher stats. Because there is such a large spectrum of Pokemon abilities, we expect a large standard deviation and in turn a large margin of error when calculating confidence intervals.
  
  
**Plots to Illustrate Results:** 
```{r}
library(ggplot2)
library(fmsb)
```

 

